sudo: required
dist: trusty

language:
    - c
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - valgrind
    - clang
    - gcc
    - gcc-6
    - fuse
    - libfuse2
    - libfuse-dev
before_install:
   - pip install pip==8.1.1 && pip3 install pip==8.1.1
install: test/travis-install.sh
script: test/travis-build.sh

